# Generated by Django 5.0.1 on 2024-01-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.TextField()),
                ('answer_choice_a', models.TextField()),
                ('answer_choice_b', models.TextField()),
                ('answer_choice_c', models.TextField()),
                ('answer_choice_d', models.TextField()),
                ('chosen_answer', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
